language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
notifications:
  email: false
before_script: ./lib/jshint ./tests/*.js && ./lib/jshint ./app/*.js
script: ./lib/intern/intern-client config=tests/internCloud && ./lib/intern/intern-runner config=tests/internCloud
