define({
	"root": {
		answer_almost: "Almost there! Expected answer: <b>%s</b> (%s letter(s) difference)",
		answer_correct: "Well done!",
		answer_wrong: "Wrong answer! Expected answer: <b>%s</b>",
		create_additem: "Add item slot",
		create_busycreating: "Creating dataset...",
		create_buttoncreate: "Create dataset",
		create_header: "Create new dataset",
		create_remove: "Remove",
		error_datasetnamenotunique: "This name is already used for another dataset!",
		error_emailnotunique: "An account is already registered for this email adress.",
		error_logout: "Something went wrong, so you have been signed out. Contact the administrator if this errors keeps occuring.",
		error_nointernet: "Couldn't connect to the internet, please reconnect and try again.",
		error_nointernet_register: "You cannot register offline.\n Please check your internet connection",
		error_notenteredallfields: "You have not entered all fields!",
		error_passwordincorrect: "Incorrect password.",
		error_subjectnamenotunique: "This subject already exists!",
		error_unsupportedfiletype: "This file type is not supported.",
		error_usernameincorrect: "This username does not exist.",
		error_usernamenotunique: "This username is already in use. Please choose another username.",
		general_close: "Close",
		general_correct: "Correct",
		general_help: "Help",
		general_logout: "Sign off",
		general_progress: "Progress",
		general_quit: "Quit program",
		general_words: "words",
		index_forspeakers1: "for ",
		index_forspeakers2: " speakers",
		label_answer: "Answer",
		label_customsubject: "Name of the new subject",
		label_dateofbirth: "Date of birth",
		label_emailaddress: "Email address",
		label_firstname: "First name",
		label_gender: "Gender",
		label_genderfemale: "Female",
		label_gendermale: "Male",
		label_hint: "Hint (optional)",
		label_language: "Language",
		label_lastname: "Last name",
		label_name: "Name",
		label_password: "Password",
		label_passwordconfirm: "Confirm password",
		label_question: "Question",
		label_strength: "Strength",
		label_subject: "Subject",
		label_username: "Username",
		learning_done: "Done!",
		learning_pause: "Pause lesson",
		learning_stop: "Stop lesson",
		learning_timeup: "You are done with this session!",
		login_buttonlogin: "Sign in",
		login_checking: "Checking login...",
		login_forgotpassword: "I forgot my password.",
		login_loggingin: "Logging in...",
		login_needhelp: "Need help?",
		login_pleaselogin: "Please sign in below.",
		login_register: "I want to register a new account.",
		login_synchronizing: "Synchronizing account...",
		login_welcome: "Welcome to the SlimStampen application.",
		message_default: "Unknown message",
		message_enterorwait: "Press Enter to continue or wait %s seconds.",
		navigation_download: "Download",
		navigation_new: "New",
		navigation_open: "Open",
		navigation_upload: "Upload",
		open_busysaving: "Saving dataset...",
		open_buttonsave: "Save dataset",
		open_dropfile: "Drop a XLSX / XLSM / XLSB / ODS / XLS / XML file below:",
		open_headerenterinformation: "Enter the dataset information",
		open_headerselectfile: "Select a dataset file",
		placeholder_customsubject: "Add to a new subject",
		placeholder_datasetname: "Name of the dataset",
		placeholder_gender: "Select your gender",
		placeholder_subject: "Select a subject",
		placeholder_typeanswerhere: "Type here your answer...",
		profile_header: "Profile",
		register_buttoncancel: "Cancel and return to log in screen",
		register_buttonregister: "Confirm and register account",
		register_header: "Account registration",
		settings_buttonsave: "Save settings",
		settings_changeinfo: "Change profile information",
		settings_changelanguage: "Change interface language",
		settings_changepassword: "Change password",
		settings_header: "Settings",
		success_change_language: "Your language settings have been saved.",
		success_createdataset: "You have succesfully created a new dataset.",
		success_delete_dataset: "You have succesfully deleted the dataset",
		success_login: "You have succesfully signed in.",
		success_loginautomatic: "Welcome back %s! You have been logged in automatically.",
		success_logout: "You have been signed out.",
		success_opendataset: "You have succesfully loaded a new dataset into the system.",
		success_register: "You have succesfully registered a new account. You can sign in here below.",
		tutorial_typeanswer: "<b>Type the answer:</b> %s"
	},
	"nl": {
		answer_almost: "Bijna! Verwachte antwoord: <b>%s</b> (%s letter(s) verschil)",
		answer_correct: "Goed gedaan!",
		answer_wrong: "Incorrect! Verwachte antwoord: <b>%s</b>",
		create_additem: "Plaats voor vraag toevoegen",
		create_busycreating: "Dataset wordt gecreëerd...",
		create_buttoncreate: "Dataset aanmaken",
		create_header: "Creëer een nieuwe dataset",
		create_remove: "Wissen",
		error_datasetnamenotunique: "Er bestaat al een dataset met deze naam!",
		error_emailnotunique: "Er is al een gebruiker geregistreerd op dit emailadres.",
		error_logout: "Er is een fout opgetreden, en je bent afgemeld. Neem contact op met de beheerder in het geval deze fout blijft voorkomen.",
		error_nointernet: "Kan niet verbinden met het internet, herstel de verbinding en probeer het opnieuw.",
		error_nointernet_register: "Je kan geen account registreren zonder internet.\n Controleer je verbinding en probeer het opnieuw.",
		error_notenteredallfields: "Je hebt niet alle velden ingevuld!",
		error_passwordincorrect: "Onjuist wachtwoord.",
		error_subjectnamenotunique: "Dit vak bestaat al!",
		error_unsupportedfiletype: "Dit bestandstype wordt niet ondersteund.",
		error_usernameincorrect: "Deze gebruikersnaam bestaat niet.",
		error_usernamenotunique: "Deze gebruikersnaam is al in gebruik. Kies een andere gebruikersnaam.",
		general_close: "Sluiten",
		general_correct: "Goed beantwoord",
		general_help: "Help",
		general_logout: "Afmelden",
		general_progress: "Voortgang",
		general_quit: "Programma sluiten",
		general_words: "woorden",
		index_forspeakers1: "voor ",
		index_forspeakers2: " sprekenden",
		label_answer: "Antwoord",
		label_customsubject: "Naam van het nieuwe vak",
		label_dateofbirth: "Geboortedatum",
		label_emailaddress: "Emailadres",
		label_firstname: "Voornaam",
		label_gender: "Geslacht",
		label_genderfemale: "Vrouw",
		label_gendermale: "Man",
		label_hint: "Hint (optioneel)",
		label_language: "Taal",
		label_lastname: "Achternaam",
		label_name: "Naam",
		label_password: "Wachtwoord",
		label_passwordconfirm: "Wachtwoord bevestigen",
		label_question: "Vraag",
		label_strength: "Beheersing",
		label_subject: "Vak",
		label_username: "Gebruikersnaam",
		learning_done: "Klaar!",
		learning_pause: "Les pauzeren",
		learning_stop: "Les stoppen",
		learning_timeup: "Je bent klaar met deze les!",
		login_buttonlogin: "Aanmelden",
		login_checking: "Gebruikersgegevens controleren...",
		login_forgotpassword: "Ik ben mijn wachtwoord vergeten.",
		login_loggingin: "Inloggen...",
		login_needhelp: "Hulp nodig?",
		login_pleaselogin: "Je kunt je hier aanmelden.",
		login_synchronizing: "Account synchroniseren...",
		login_register: "Ik wil een nieuwe gebruiker registeren.",
		login_welcome: "Welkom bij de SlimStampen-applicatie",
		message_default: "Onbekend bericht",
		message_enterorwait: "Druk op Enter of wacht %s seconden.",
		navigation_download: "Downloaden",
		navigation_new: "Nieuw",
		navigation_open: "Openen",
		navigation_upload: "Uploaden",
		open_busysaving: "Dataset wordt opgeslagen...",
		open_buttonsave: "Dataset opslaan",
		open_dropfile: "Sleep hieronder een bestand van het type XLSX / XLSM / XLSB / ODS / XLS / XML:",
		open_headerenterinformation: "Geef informatie op voor de dataset",
		open_headerselectfile: "Selecteer een dataset-bestand",
		placeholder_customsubject: "Aan een nieuw vak toevoegen",
		placeholder_datasetname: "Naam van de dataset",
		placeholder_gender: "Selecteer je geslacht",
		placeholder_subject: "Kies een vak",
		placeholder_typeanswerhere: "Typ het antwoord hier...",
		profile_header: "Profiel",
		register_buttoncancel: "Annuleren en terug naar aanmeldscherm",
		register_buttonregister: "Bevestigen en gebruiker aanmaken",
		register_header: "Gebruikersregistratie",
		settings_buttonsave: "Instellingen opslaan",
		settings_changeinfo: "Profielgegevens veranderen",
		settings_changelanguage: "Programmataal veranderen",
		settings_changepassword: "Wachtwoord veranderen",
		settings_header: "Instellingen",
		success_change_language: "Je taalinstellingen zijn succesvol opgeslagen.",
		success_createdataset: "De nieuwe dataset is succesvol gecreëerd.",
		success_delete_dataset: "De dataset is succesvol verwijderd.",
		success_login: "Je bent succesvol aangemeld.",
		success_loginautomatic: "Welkom terug %s! Je bent automatisch aangemeld.",
		success_logout: "Je bent succesvol afgemeld.",
		success_opendataset: "De nieuwe dataset is succesvol in het systeem geladen.",
		success_register: "De registratie is voltooid. Je kunt je hieronder aanmelden.",
		tutorial_typeanswer: "<b>Typ het antwoord:</b> %s"
	},
	"ar": {
		answer_almost: "تقريبا! الإجابة المتوقعة: <b>%s</b> (الفرق  %s  حرف )",
		answer_correct: "! أحسنت",
		answer_wrong: "إجابة خاطئة! الإجابة المتوقعة: <b>%s</b> ",
		create_additem: "إضافة سطر",
		create_busycreating: "إنشاء مجموعة البيانات ...",
		create_buttoncreate: "إنشاء مجموعة البيانات ",
		create_header: "إنشاء مجموعة بيانات جديدة",
		create_remove: "حذف",
		error_datasetnamenotunique: "هذا الإسم مستختدم من قبل مجموعة بيانات أخرى",
		error_emailnotunique: "هذا  البريد الإلكتروني  مسجل ",
		error_logout: "حدث خطأ ما، لذلك كنت قد تم تسجيل الخروج. اتصل بالإدارة اذا استمر هذا الخطأ في الحدوث",
		error_notenteredallfields: "لم يتم إدخال كافة المعلومات المطلوبة.",
		error_nointernet: "Couldn't connect to the internet, please reconnect and try again.",
		error_nointernet_register: "You cannot register offline.\n please check your internet connection",
		error_passwordincorrect: "كلمة المرور غير صحيحة.",
		error_unsupportedfiletype: " هذا النوع من الملفات ليس معتمد",
		error_usernameincorrect: "هذا الإسم غير موجود.",
		error_usernamenotunique: "هذا المستخدم موجود، يرجى اختيار اسم مستخدم آخر",
		general_close: "إغلاق",
		general_correct: "إجابة صحيحة",
		general_help: "مساعدة",
		general_logout: "تسجيل خروج",
		general_progress: "تقدم",
		general_quit: "إنهاء البرنامج",
		general_words: "كلمات",
		index_forspeakers1: "for ",
		index_forspeakers2: " speakers",
		label_answer: "الإجابة",
		label_dateofbirth: "تاريخ الميلاد",
		label_emailaddress: " البريد الإلكتروني",
		label_firstname: "الإ سم",
		label_gender: "الجنس",
		label_genderfemale: "أنثى",
		label_gendermale: "ذكر",
		label_hint: "تلميح (اختياري)",
		label_language: "اللغة",
		label_lastname: "اللقب",
		label_name: "الإسم",
		label_password: "كلمة المرور",
		label_passwordconfirm: "تأكيد كلمة المرور",
		label_question: "السؤال",
		label_strength: "القوة",
		label_subject: "الموضوع",
		label_username: "اسم المستخدم",
		learning_done: "انتهى!",
		learning_pause: "إيقاف مؤقت",
		learning_stop: "إيقاف الحصة",
		learning_timeup: "لقد انهيت هذه الحصة",
		login_buttonlogin: "تسجيل الدخول",
		login_forgotpassword: "لقد نسيت كلمة المرور.",
		login_needhelp: "بحاجة الى مساعدة؟",
		login_pleaselogin: "يرجى تسجيل الدخول أدناه.",
		login_register: ".أريد  تسجيل حساب جديد",
		login_welcome: "مرحبا بك في تطبيق سليمستامبن.",
		message_default: "رسالة مجهولة",
		message_enterorwait: "اضغط على زر الإدخال  للمتابعة أو انتظر %s ثواني",
		navigation_download: "تنزيل",
		navigation_new: "جديد",
		navigation_open: "فتح",
		navigation_upload: "تحميل",
		open_busysaving: "...حفظ البيانات",
		open_buttonsave: "حفظ مجموعة البيانات",
		open_dropfile: "ضع ملف XLSX / XLSM / XLSB / ODS / XLS / XML أسفله:",
		open_headerenterinformation: "إدخال المعلومات المتعلقة بمجموعة البيانات",
		open_headerselectfile: "إختر ملف مجموعة البيانات",
		placeholder_datasetname: "إسم مجموعة البيانات",
		placeholder_gender: "اختر جنسك",
		placeholder_subject: "اختيار موضوع",
		placeholder_typeanswerhere: "أكتب الإجابة....",
		profile_header: "Profile",
		register_buttoncancel:"إلغاء والعودة إلى شاشة تسجيل الدخول",
		register_buttonregister: "تأكيد و تسجيل الحساب",
		register_header: "تسجيل حساب",
		settings_buttonsave: "حفظ الإعدادات",
		settings_changeinfo: "تغيير معلومات الحساب الشخصي",
		settings_changepassword: "تغيير كلمة السر",
		settings_header: "الإعدادات",
		success_change_language: "Your language settings have been saved.",
		success_createdataset: "لقد نجحت في إنشاء مجموعة بيانات جديدة",
		success_delete_dataset: "You have succesfully deleted the dataset",
		success_login: "قمت بتسجيل الدخول بنجاح.",
		success_loginautomatic: "مرحبا بعودتك. %s!  لقد تم تسجيل الدخول تلقائيا..",
		success_logout: "لقد تم تسجيل خروجك.",
		success_opendataset: "لقد تحميل مجموعة بيانات جديدة إلى البرنامج بنجاح.",
		success_register: "لقد سجلت حسابا جديدا بنجاح. يمكنك تسجيل الدخول  أدناه..",
		tutorial_typeanswer: "<b>أكتب الإجابة التالية:</b> %s"
	}
});
