define({
	"root": {
		answer_correct: "Well done!",
		answer_almost: "Almost there! Expected answer: <b>%s</b> (%s letter(s) difference)",
		answer_wrong: "Wrong answer! Expected answer: <b>%s</b>",
		tutorial_typeanswer: "<b>Type the answer:</b> %s",
		general_words: "words",
		general_progress: "Progress",
		learning_done: "Done!",
		message_enterorwait: "Press Enter to continue or wait %s seconds.",
		general_correct: "Correct",
		general_help: "Help",
		learning_pause: "Pause lesson",
		learning_stop: "Stop lesson",
		placeholder_typeanswerhere: "Type here your answer...",
		navigation_new: "New",
		navigation_open: "Open",
		navigation_download: "Download",
		navigation_upload: "Upload",
		general_quit: "Quit program",
		error_notenteredallfields: "You have not entered all fields!",
		label_name: "Name",
		label_subject: "Subject",
		label_language: "Language",
		placeholder_name: "Name of the dataset",
		placeholder_subject: "Select a subject",
		create_buttoncreate: "Create dataset",
		create_question: "Question",
		create_answer: "Answer",
		create_hint: "Hint (optional)",
		create_remove: "Remove",
		create_additem: "Add item",
		create_busycreating: "Creating dataset...",
		error_datasetnamenotunique: "This name is already used for another dataset!",
		error_requirefail: "Failed to require %s through AMD.",
		login_welcome: "Welcome to the SlimStampen application.",
		login_pleaselogin: "Please sign in below.",
		label_username: "Username",
		label_password: "Password",
		login_buttonlogin: "Sign in",
		login_needhelp: "Need help?",
		login_forgotpassword: "I forgot my password.",
		login_register: "I want to register a new account.",
		error_usernameincorrect: "This username does not exist.",
		error_passwordincorrect: "Incorrect password.",
		open_dropfile: "Drop a XLSX / XLSM / XLSB / ODS / XLS / XML file below:",
		open_headerselectfile: "Select a dataset file",
		open_headerenterinformation: "Enter the dataset information",
		open_buttonsave: "Save dataset",
		open_busysaving: "Saving dataset...",
		error_unsupportedfiletype: "This file type is not supported.",
		register_header: "Account registration",
		label_emailaddress: "Email address",
		label_passwordconfirm: "Confirm password",
		label_gender: "Gender",
		placeholder_gender: "Select your gender",
		label_gendermale: "Male",
		label_genderfemale: "Female",
		label_dateofbirth: "Date of birth",
		register_buttonregister: "Confirm and register account",
		register_buttoncancel: "Cancel and return to log in screen",
		error_usernamenotunique: "This username is already in use. Please choose another username.",
		error_emailnotunique: "An account is already registered for this email adress.",
		learning_timeup: "You are done with this session!",
		index_forspeakers1: "for ",
		index_forspeakers2: " speakers",
		label_strength: "Strength",
		success_createdataset: "You have succesfully created a new dataset.",
		success_opendataset: "You have succesfully loaded a new dataset into the system.",
		message_default: "Unknown message"
	},
	"nl": {
		answer_correct: "Goed gedaan!",
		answer_almost: "Bijna! Verwachte antwoord: <b>%s</b> (%s letter(s) verschil)",
		answer_wrong: "Incorrect! Verwachte antwoord: <b>%s</b>",
		tutorial_typeanswer: "<b>Typ het antwoord:</b> %s",
		general_words: "woorden",
		general_progress: "Voortgang",
		learning_done: "Klaar!",
		message_enterorwait: "Druk op Enter of wacht %s seconden.",
		general_correct: "Goed beantwoord",
		general_help: "Help",
		learning_pause: "Les pauzeren",
		learning_stop: "Les stoppen",
		placeholder_typeanswerhere: "Typ het antwoord hier...",
		navigation_new: "Nieuw",
		navigation_open: "Openen",
		navigation_download: "Downloaden",
		navigation_upload: "Uploaden",
		general_quit: "Programma sluiten",
		error_notenteredallfields: "Je hebt niet alle velden ingevuld!",
		label_name: "Naam",
		label_subject: "Vak",
		label_language: "Taal",
		placeholder_name: "Naam van de dataset",
		placeholder_subject: "Kies een vak",
		create_buttoncreate: "Dataset aanmaken",
		create_question: "Vraag",
		create_answer: "Antwoord",
		create_hint: "Hint (optioneel)",
		create_remove: "Wissen",
		create_additem: "Vraag toevoegen",
		create_busycreating: "Dataset wordt gecreëerd...",
		error_datasetnamenotunique: "Er bestaat al een dataset met deze naam!",
		error_requirefail: "Fout bij het laden van %s in AMD.",
		login_welcome: "Welkom bij de SlimStampen-applicatie",
		login_pleaselogin: "Je kunt je hier aanmelden.",
		label_username: "Gebruikersnaam",
		label_password: "Wachtwoord",
		login_buttonlogin: "Aanmelden",
		login_needhelp: "Hulp nodig?",
		login_forgotpassword: "Ik ben mijn wachtwoord vergeten.",
		login_register: "Ik wil een nieuwe gebruiker registeren.",
		error_usernameincorrect: "Deze gebruikersnaam bestaat niet.",
		error_passwordincorrect: "Onjuist wachtwoord.",
		open_dropfile: "Sleep hieronder een bestand van het type XLSX / XLSM / XLSB / ODS / XLS / XML:",
		open_headerselectfile: "Selecteer een dataset-bestand",
		open_headerenterinformation: "Geef informatie op voor de dataset",
		open_buttonsave: "Dataset opslaan",
		open_busysaving: "Dataset wordt opgeslagen...",
		error_unsupportedfiletype: "Dit bestandstype wordt niet ondersteund.",
		register_header: "Gebruikersregistratie",
		label_emailaddress: "Emailadres",
		label_passwordconfirm: "Wachtwoord bevestigen",
		label_gender: "Geslacht",
		placeholder_gender: "Selecteer je geslacht",
		label_gendermale: "Man",
		label_genderfemale: "Vrouw",
		label_dateofbirth: "Geboortedatum",
		register_buttonregister: "Bevestigen en gebruiker aanmaken",
		register_buttoncancel: "Annuleren en terug naar aanmeldscherm",
		error_usernamenotunique: "Deze gebruikersnaam is al in gebruik. Kies een andere gebruikersnaam.",
		error_emailnotunique: "Er is al een gebruiker geregistreerd op dit emailadres.",
		learning_timeup: "Je bent klaar met deze les!",
		index_forspeakers1: "voor ",
		index_forspeakers2: " sprekenden",
		label_strength: "Beheersing",
		success_createdataset: "De nieuwe dataset is succesvol gecreëerd.",
		success_opendataset: "De nieuwe dataset is succesvol in het systeem geladen.",
		message_default: "Onbekend bericht"
	},
	"arab": {
		answer_correct: "أحسنت!",
		answer_almost: "(رسائل <b>%2$s</b> زمني الفارق) <b>%1$s</b> :هناك تقريبا! الإجابة المتوقعة"
	}
});